### ISSUE TITLE
How do I define "CloudType" and the WorxCloud object

### ISSUE THREAD

**Issue by Hickori** [MTrab/pyworxcloud#104]
When I am doing cloud.connect() with this code:

```
from pyworxcloud import WorxCloud
import requests

cloud = WorxCloud("MAIL@gmail.com", "PASS", "worx")
cloud.connect()
```

I am getting this exception: TypeError: WorxCloud.connect() missing 1 required positional argument: 'dev_id'

I belive that the reason is that I have the work CloudType, but I dont know how to properly declare a "CloudType"

Thanks in advance!
Best regards Max

**Comment by MTrab** [comment]
Documentation is not up-to-date as this is undergoing a COMPLETE rewrite.
The current code is NOT production ready and have ALOT of flaws.
Pin your version to 2.1.23 and the documentation should be as needed again - althou that version is almost guaranteed not to work due to HUGE API changes

**Comment by MTrab** [comment]
As said - this code is not in a working state right now, because of the API changes.
I'm putting the last finishing touches in another project in these days, after which I'll "throw my love" towards this project again.
