### ISSUE TITLE
Not aligned requirements file

### ISSUE THREAD

**Issue by fra87** [MTrab/pyworxcloud#130]
The requirements.txt file is not aligned with the dependencies in pyproject.toml.

I'm not sure if this is because the requirements.txt file is outdated, but I think that it is better to either align it or to remove it from the repo (of course with a very low priority; after all, very few people will use it).

In addition, I noticed that when I created manually a venv to run the examples I also had to pull the tzdata package; maybe it is an implicit dependency for poetry, but in requirements.txt I had to add it otherwise the python script complained

Thank you

**Comment by MTrab** [comment]
It should just be removed as it's no longer in use
