### ISSUE TITLE
Python version requirement

### ISSUE THREAD

**Issue by henfri** [MTrab/pyworxcloud#131]
Hello Marlene,

thanks for your work on updating to v3!
I have one issue though: 
I (and the target audience) do not have python 3.10. I have "patched" pyworxcloud to accept 3.9 and it seems to work. At least:
```
cloud.connect()

print(vars(cloud))

cloud.disconnect()
```

Can you tell me whether 3.10 is really needed?

Best regards,
Hendrik

**Comment by MTrab** [comment]
Ehm?!

https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/__init__.py#L37

Don't know what you mean

**Comment by henfri** [comment]
Ah, great.

> Don't know what you mean

Really? 
https://github.com/MTrab/pyworxcloud/blob/master/pyworxcloud/__init__.py#L38 

In fact, I am still on pyworxcloud  3.0.1 as this installed via pip

and there in fact L37 also refers to 3.10:
https://github.com/MTrab/pyworxcloud/blob/63f73328116442fd50912d0d077f50f0d5d77e2d/pyworxcloud/__init__.py#L37

Greetings,
Hendrik

**Comment by MTrab** [comment]
Yeah - the text string is wrong - will be fixed.
But it is fully 3.9 compatible, also via pip (at least I have installed it on a 3.9 test setup I have) - so perhaps you should just update ;)

**Comment by henfri** [comment]
See my edit:
https://github.com/MTrab/pyworxcloud/blob/6f5446f8a2e9540736836547396d10201f028246/pyproject.toml#L22

pip does not install 3.1.3 for me. I suspect that ^^  is why?
Here https://pypi.org/project/pyworxcloud/ it also says that 3.10 is needed.

Greetings,
Hendrik

**Comment by MTrab** [comment]
Hmmm - I must have forgot that setting. But I can install it via PIP on a 3.9 system just fine

**Comment by henfri** [comment]
Hm... I am not sure what I am doing wrong:
```
pip3 install pyworxcloud==3.1.3
ERROR: Could not find a version that satisfies the requirement pyworxcloud==3.1.3 (from versions: 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17.dev1, 2.1.17, 2.1.18, 2.1.19, 2.1.20, 2.1.22, 2.1.23, 3.0.1)
ERROR: No matching distribution found for pyworxcloud==3.1.3

python --version
Python 3.9.5
```

That is in windows.

In Debian:
```
pip3 install pyworxcloud==3.1.3
ERROR: Could not find a version that satisfies the requirement pyworxcloud==3.1.3
ERROR: No matching distribution found for pyworxcloud==3.1.3
```

If I do not specify the version, I get 3.0.1 (just like in Windows).

Also, if you follow what's written in https://pypi.org/project/pyworxcloud/, the behaviour that I observe is normal, and the fact that you get 3.1.3 is abnormal, isn't it?

Greetings,
Hendrik

**Comment by MTrab** [comment]
Certainly is strange, agreed 

Will be fixed in next release - won't do that tonight though as I have a few tasks on my todo the check on before releasing the next version

**Comment by henfri** [comment]
No problem. No urgency from my side.

Thanks again!!
