### ISSUE TITLE
Can I use this as a bridge

### ISSUE THREAD

**Issue by thornick** [MTrab/pyworxcloud#133]
First of all great project - wor(x)ks right away!
Not really an issue just a question:
The season started and to my surprise I see that certificates for mqtt don't work anymore with Worx.
You adapted the code to handle the new process. But all my stuff is based on MQTT means somehow I need to bridge or forward the messages to my mqtt server.
Can you give me a hint where in your code I could add this logic or are there any plans in that direction already?
I see  self._forward_on_message is triggered and calls on_update, maybe there?
but don't know where to put in the additional connection part.

**Comment by MTrab** [comment]
Sorry - I cannot. The new way uses tokens and socket connections rather than a normal MQTT connection

**Comment by thornick** [comment]
ok, thanks
can you explain how I can access the payload in the test_async.py example

def receive_data(
    name: str, device: DeviceHandler  # pylint: disable=unused-argument
) -> None:
    """Callback function when the MQTT broker sends new data."""
    print("Got data on MQTT from " + name)

**Comment by MTrab** [comment]
Haven't had time to update the docs for v3 yet. But take a look in test.py
