### ISSUE TITLE
[FR] Support for "One time schedule"

### ISSUE THREAD

**Issue by Mincka** [MTrab/pyworxcloud#14]
I am a user of [MTrab/landroid_cloud](https://github.com/MTrab/landroid_cloud) and it looks like that this upstream project does not yet support the "One time schedule" feature. It's the ability to start the mower for a defined number of hours, up to 12 h on my WR165E. It would be great to have it in [MTrab/landroid_cloud](https://github.com/MTrab/landroid_cloud) and then hopefully in https://github.com/Barma-lej/halandroid. Thank you for this project. 👍

Additional note:
I think the duration of the "One time schedule" is a setting and not a parameter of the specific command. I can update the number of hours without starting the "One time schedule" sequence. In this case, it would mean an additional setting for `cfg` + an additional `cmd`code to find and implement.

Official documentation:
https://wiki.worx.com/en/landroid-schedule-1

![image](https://user-images.githubusercontent.com/6184289/166107973-4bf990e6-8fde-4b09-a52b-43cb4cf06819.png)
Screenshot taken from https://github.com/MTrab/landroid_cloud/issues/59#issuecomment-867009803

**Comment by MTrab** [comment]
Will be available with the upcoming version 2
