### ISSUE TITLE
last_status is None

### ISSUE THREAD

**Issue by TheDOC123** [MTrab/pyworxcloud#146]
Yesterdays commit (https://github.com/MTrab/pyworxcloud/commit/e290a634d473b78721c98f4427aa2495d0509d28) breaks the library for me:

My last_status is None:
```

  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 22, in __init__
    self["index"] = data["last_status"]["payload"]["dat"]["lz"]
TypeError: 'NoneType' object is not subscriptable
```
`
Capability data: { ..........
'last_status': None, 'model': {'code': 'WR105SI.1', .............. }
`

**Comment by MTrab** [comment]
That seems very odd

**Comment by MTrab** [comment]
Will be fixed in next release.
Doing some bug investigation related to another issue, so wont publish a release until I know if that other issue relates to this module or it is pure API

**Comment by TheDOC123** [comment]
It COULD be because this mower was offline for half a year now. Just a guess.

**Comment by TheDOC123** [comment]
Problem appeared again in a different position after updating to latest version:

  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/utils/zone.py", line 22, in __init__
    if not "payload" in data["last_status"]:
TypeError: argument of type 'NoneType' is not iterable

data["last_status"] is None.

So my uneducated guess on fixing it would be changing above line to:
`        if data["last_status"] is None or not "payload" in data["last_status"]:
            return       `
