### ISSUE TITLE
Update vs. getStatus

### ISSUE THREAD

**Issue by immek** [MTrab/pyworxcloud#15]
Hi,
First of all - thank you for your great work here!
I've got a question - what is the difference between method _update_ and getStatus. Only _getStatus_ is "bannable"? Can I call _update_ how often I want but there will be new data only if server sends any since the previous call?

**Comment by MTrab** [comment]
Update will be deprecated in near future ;)

**Comment by immek** [comment]
Er.. ok ;-) . So could you please explain more why and how does it work? How can I update as often as possible without actively requesting new data (just relying on whatever server pushes)?

**Comment by MTrab** [comment]
Data is saved in local objects, so if server haven't pushed any data, then you'd use getstatus.
But calling this too often will result in a ban

**Comment by MTrab** [comment]
No purpose. Only leftover for the beginning of the project.
Isn't used anymore, hence the deprecation in an upcoming releases

**Comment by MTrab** [comment]
DO NOT force updates! It will get you banned!
No matter what method you use.

And shouldn't be nessecary, as the mower will report new states when mowing

**Comment by immek** [comment]
Ok, so I guess I've been very, very lucky :-D. For over a year I've been happily using my script with 60 - 300s intervals (depending on the current status). Today I've checked HA code and found that the default getStatus interval there is 30 minutes.. So that is why I've started to ask questions about the difference between update and getStatus.. Before this discovery I was thinking about reducing my interval, but now I don't think it would be a good idea ;). 
Did you make any analysis - how often landroid itself make a report (without forcing an update)? Is it also related to current status (charging, mowing)? Errors are reported right away?

**Comment by MTrab** [comment]
It differs how often it updates - haven't got some exact measurements, other than it'll report the status when there is changes.

And yes, if you haven't experienced bans, then you are VERY lucky - there's alot that have experienced bans when calling the update too often - that's why we added throtteling to getStatus

**Comment by immek** [comment]
Well.. bye bye my smooth grafana charts ;). I will rewrite my scripts. 

Thank you for the explaination.
