### ISSUE TITLE
How to send mover to specific zone

### ISSUE THREAD

**Issue by MarkResting** [MTrab/pyworxcloud#164]
Hi,
not sure if this is the right way to ask this question, but i don't find a better place,....

First of all THX a lot for you work!!!!!

I can already start and stop my mover (worx) but i'm not able to send him to a specific Zone. is there any excample or someone who can help me on that?
I'm using just the phyton script without IO Broaker.

Thx a lot up front!
Mark

**Comment by MTrab** [comment]
Use the setzone function, specifying the zone as int 0 to 3

**Comment by MarkResting** [comment]
First of all MANY MANY THX for that quick response!!!!

Hm,.... now I'm getting always that the mover is offlinee,... but he isn't,.... at least i was able to send him last week,... I'm getting an update, but when i try to start it, it's telling me, that it's offline :-(

**Comment by MTrab** [comment]
Offline/online state is reported by API and is not a calculated state.

**Comment by MarkResting** [comment]
ok, reboot soved this, noe i'm getting this as result after starting the setzone:

cloud.setzone("SERIAL_NUMBER",0)

raise RequestException("Cannot request this zone as it is not defined.")

**Comment by MTrab** [comment]
Have you defined any zones?
From the error I guess not

**Comment by MarkResting** [comment]
i tried to download the newest version,... there the error looks like this:

TypeError: 'NoneType' object is not iterable

maybe i'm doin'g something totally wrong?!?
Sorry for all these questions,...

**Comment by MTrab** [comment]
No idea what you might be doing wrong.
As far as I know it should work as intended (at least it does when I have been testing

**Comment by MarkResting** [comment]
ok, start stop is working now.
set zone not :-(

always the "not defined" Error :-(


  File ~\pyworxcloud-3.1.4\pyworxcloud-3.1.4\pyworxcloud\__init__.py:682 in setzone
    raise RequestException("Cannot request this zone as it is not defined.")

RequestException: Cannot request this zone as it is not defined.

**Comment by MTrab** [comment]
Oh - you are on an old version of pyworxcloud where this didn't work.
Please update to the latest version

**Comment by MarkResting** [comment]
Hi, sorry for the late answer! 
I moved over and it works now! 

Thax a lot for that nice implementation!!!
