### ISSUE TITLE
AttributeError: 'Client' object has no attribute '_on_pre_connect'. Did you mean: 'on_pre_connect'?

### ISSUE THREAD

**Issue by MarkResting** [MTrab/pyworxcloud#171]
Hi,
after i was able to get pyworxcloud running on windows I tried the setup on a linux ubuntu.

I'm getting the above Error,... Is there an issue with the Versions in combination with paho.mqtt.python?
I installed the latest Versions.

Would love if someone could help.

If you need more Information, let me know.

Thex a lot!!!!

Mark

**Comment by MarkResting** [comment]
OMG, I installed it with:
`phyton setup.py`
Was not aware that there is a differen,... SORRY. 

So the Issue is solved ;-) Thx a lot for that nice development and the very good support!

Nex thing on my agenda is to by a coffee for you!

Thx a lot, Mark.

P.S.: Mybe a stupid question, but is it possible to use an existing MQTT Server?

**Comment by MTrab** [comment]
Existing MQTT server? What do you mean?
It uses AWS MQTT server as that's what Positec has decided to use - no way to change that to anything else.

**Comment by MarkResting** [comment]
I just thougt that i can avoid the insatllation of this paho MQTT due to i already have an MQTT Server running. But looks like not.
Sorry for the stupid question, i'm new to all of this.

May be another question, hope it's not steeling all of youre time,...
I saw in the UTILS Folder a lot of *.py functions looks like they can give me already Informatioins about the battery and so on.

Maybe you can give me a short excample how i can use them?

Kind regards,
Mark

**Comment by MTrab** [comment]
PahoMQTT is the connector needed to connect _TO_ an MQTT server - it's not a server.

**Comment by MarkResting** [comment]
Yeah, got that. Thx.

And is there an Excample for the other functions within UTILS?

**Comment by MTrab** [comment]
Not currently, no - and this module requires a bit of programming experience.

**Comment by MarkResting** [comment]
Do you know if there is still a limit for update requests? or can i rrefresh that every 30 seconds?

**Comment by MTrab** [comment]
There is no need, as the module handles this by itself.
DO NOT FORCE REFRESH like that
