### ISSUE TITLE
example.py still uses update()

### ISSUE THREAD

**Issue by henfri** [MTrab/pyworxcloud#19]
Hello Marlene,

with 1.4.19 update() is deprecated. But example.py still uses it.
Could you please update example.py?

Best regards,
Hendrik

**Comment by MTrab** [comment]
Will be updated later, but just delete whatever calls you have to update

**Comment by henfri** [comment]
Ok, thanks.

Can you explain, when tryToPoll() should be called?

**Comment by MTrab** [comment]
Ideally, never ;)

**Comment by henfri** [comment]
Hm, what is the purpose then?

**Comment by MTrab** [comment]
Can't remember right now

**Comment by MTrab** [comment]
Closed because of upcoming version 2 with major changes
