### ISSUE TITLE
edgecut stopped working after upgrade

### ISSUE THREAD

**Issue by sbias** [MTrab/pyworxcloud#50]
After upgrading to v2.1.2 the edgecut service does not do anything at all.
there is no error, no log, no reaction of the mower.

This is how i call the service:

service: landroid_cloud.edgecut
target:
  entity_id: vacuum.rasimir

**Comment by MTrab** [comment]
Okay - will check what's going on.

**Comment by sbias** [comment]
(opps, i just noticed i'v created this ticket in the wrong repo, this might belong to https://github.com/MTrab/landroid_cloud , please tell me if i should move it, sorry for that )

**Comment by MTrab** [comment]
Still not sure if this is related to the pyworxcloud or the actual integration, still investigating.
I'll move it if this is not the correct repo for the fix :)

**Comment by MTrab** [comment]
Looks like it isn't the only service that stopped working.
Trying to find the culprit to why this is failing
