### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by fra87** [MTrab/pyworxcloud#59]
I noticed the extension was not giving updates, and going in the logs I found this:

[uncaught_exception.txt](https://github.com/MTrab/pyworxcloud/files/9062099/uncaught_exception.txt)

Can this be linked to #58 or, in your opinion, it is different? The event happened roughly 12 hours after I restarted HA.

Best regards

**Comment by MTrab** [comment]
Looks like you might not be on latest release, as line 196 in __init__.py isn't like the error says anymore

Current line 196: https://github.com/MTrab/pyworxcloud/blob/eb41734db94b5305f93d160e3e83c182e364238e/pyworxcloud/__init__.py#L196

From the log provided:
`data = json.loads(indata)`

**Comment by MTrab** [comment]
You just need to redownload from HACS, selecting beta versions ;)

2.1.* series is beta only, due to alot of changes

**Comment by fra87** [comment]
Done, and now the pyworxcloud version is 2.1.10, while landroid_cloud is 2.1.5 :)

Thank you; I'm closing this ticket.
