### ISSUE TITLE
Request: More stable API

### ISSUE THREAD

**Issue by henfri** [MTrab/pyworxcloud#96]
Hello,

we are using your lovely package for smarthome-ng.
Unfortunately, it is a bit difficult to keep track of the changes that you do. Could you please consider the following:
- less breaking changes
- less bleeding edge (python 3.9; is that really needed?)
- depreciation warnings before changing the API
- add upgrade-guidelines when introducing breaking changes to the API

Thanks and best regards,
Hendrik

**Comment by MTrab** [comment]
There will be ALOT of breaking changes in the future - there will be a complete rewrite as I have gained access to the closed documentation from Positec.

But if this is such a big issue - why not pin the version you use?

And for Python version?! Perhaps 3.9 isn't needed, but my dev. environment is 3.9 and 3.10 as this Home Assistant is 3.10 (and this module is made primarily for use with Home Assistant)

**Comment by MTrab** [comment]
And as for the changes - trying to keep up with Positec's rewrite of the API, so that'll possibly introduce even more changes.

**Comment by henfri** [comment]
Hello,

> But if this is such a big issue - why not pin the version you use?

I did not state that it is a *big* issue, but it is a burden.
Pinning the version can lead to the API to positec not working anymore.

> And as for the changes - trying to keep up with Positec's rewrite of the API, so that'll possibly introduce even more changes.

I do not understand that. E.g. what I had to change recently was that previously creating the worx object did not take any parameters, now it takes user and pass (which were previously needed only on connect()). 
This is a change that is not triggered by changes of Positec, but your choice, I suppose.

And this is where I would wish more stability and backwards compatibility.

> Perhaps 3.9 isn't needed, but my dev. environment is 3.9 and 3.10

I tried that. There is zoneinfo that is only available in 3.9. But there is a backports.zoneinfo package (by the way: for that reason pyworxcloud crashes before it is checking for the version and requesting 3.9 or higher). So that would be solvable.
But even after adding that, there was another Issue that I do not remember. Thus, I gave up.

Best regards,
Hendrik

**Comment by MTrab** [comment]
As said - there will be HUGE changes in the near future, when I find the time to rewrite the module from scratch to comply with the correct API usage.
But then, after that, there shouldn't be huge changes unless Positec rewrites the API again.

**Comment by henfri** [comment]
Hello Marlene,

I understand that, thanks!
And thanks for the effort you put into this package. Greatly apprechiated.

Best regards,
Hendrik

**Comment by henfri** [comment]
Dear Marlene,

is the API more stable by now? 
Mowing Season is starting and we'd like to update the smarthome-ng plugin.
Could you also post a minimal example (a bit more than the test.py) in the wiki?

Thanks and best regards,
Hendrik
